name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: hyoghurt/waka-readme@dev
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
